<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bhargavi" failures="1" tests="3"
	name="TestNgListeners.com.ReportDemo" time="0.008" errors="0"
	timestamp="02 Oct 2024 10:20:59 GMT" skipped="1">
	<testcase classname="TestNgListeners.com.ReportDemo"
		name="TestFailure" time="0.002">
		<failure message="expected [true] but found [false]"
			type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at TestNgListeners.com.ReportDemo.TestFailure(ReportDemo.java:17)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
		</failure>
	</testcase> <!-- TestFailure -->
	<testcase classname="TestNgListeners.com.ReportDemo"
		name="TestSkipped" time="0.001">
		<skipped />
	</testcase> <!-- TestSkipped -->
	<testcase classname="TestNgListeners.com.ReportDemo"
		name="Testsuccess" time="0.005" />
</testsuite> <!-- TestNgListeners.com.ReportDemo -->
