<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Bhargavi" failures="1"
	tests="1" name="Default test(failed)" time="0.028" errors="0"
	timestamp="21 Oct 2024 13:16:51 GMT">
	<testcase classname="TestNgListeners.com.RetryTestUsingTestNg"
		name="test2" time="0.013">
		<failure type="java.lang.AssertionError"
			message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestNgListeners.com.RetryTestUsingTestNg.test2(RetryTestUsingTestNg.java:20)
... Removed 27 stack frames]]>
		</failure>
	</testcase> <!-- test2 -->
	<testcase classname="TestNgListeners.com.RetryTestUsingTestNg"
		name="retrytst1" time="0.0">
		<ignored />
	</testcase> <!-- retrytst1 -->
</testsuite> <!-- Default test(failed) -->
